stack: node
packageManager: npm
commit: fec39dcd9f45b6abe1fbd397b5a474922a0719bd
verifiedAt: 2026-08-20T13:56:35.856Z
commands:
  install: npm ci
  build: null
  analyze: null
  test: null
status:
  install: none
  build: none
  analyze: none
  test: none
